# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 05:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoolName', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='standardClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verboseStandardName', models.CharField(max_length=30)),
                ('school', models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.CASCADE, to='polls.School')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentName', models.CharField(max_length=30)),
                ('studentSex', models.CharField(max_length=30)),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.standardClass')),
            ],
        ),
    ]
